door_doctor/appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    path('request/', views.request_appointment, name='request_appointment'),
    path('thanks/', views.appointment_thanks, name='appointment_thanks'),
]

door_doctor/door_doctor/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('appointments/', include('appointments.urls', namespace='appointments')),
    path('about_us/', views.AboutUs.as_view(), name='about'),
    path('gallery/', views.Gallery.as_view(), name='gallery'),
    path('services/', views.Services.as_view(), name='services'),
    path('faq/', views.FAQ.as_view(), name='faq'),
    path('contact/', views.contact.as_view(), name='contact')
]

door_doctor/reviews/urls.py
from django.urls import path
from . import views
from .views import approve_review

app_name = 'reviews'

urlpatterns = [
    path('submit/', views.submit_review, name='submit_review'),
    path('thanks/', views.thank_you, name='review_thanks'),
    path('', views.review_list, name='review_list'),
    path('approve/<token>', views.approve_review, name='approve_review'),
]

door_doctor/templates/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container4">
<p>We are a family-owned and operated garage door company proudly serving our community since 1997. 
Our longevity is a testament to the trust and loyalty of our valued customers. 
Our mission is to ensure that every garage door repair and installation is seamless and stress-free. 
We are committed to providing honest, transparent assessments tailored to your specific needs, offering clear guidance on all available options. 
Our business is built on a foundation of integrity, quality craftsmanship, and exceptional customer service. 
Your satisfaction is our top priority, and we aim to leave every customer with a smile. 
</p>
</div>
{% endblock %}

door_doctor/templates/appointment_email.html
<!-- appointment_email.html -->
<!DOCTYPE html>
<html>
<head>
    <title>New Appointment Request</title>
</head>
<body>
    <h1>New Appointment Request</h1>
    <p><strong>Name:</strong> {{ name }}</p>
    <p><strong>Street:</strong> {{ street }}</p>
    <p><strong>City:</strong> {{ city }}</p>
    <p><strong>State:</strong> {{ state }}</p>
    <p><strong>ZIP Code:</strong> {{ zip_code }}</p>
    <p><strong>Phone Number:</strong> {{ phone_number }}</p>
    <p><strong>Reason for Appointment:</strong> {{ reason_for_appointment }}</p>
    <p><strong>Availability:</strong> {{ availability }}</p>
</body>
</html>

door_doctor/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Door Doctor</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'images/ddnobg.png' %}" width="64px" height="64px">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> -->

    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    <link rel="stylesheet" href="{% static 'css/custom_styles.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">

    

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark" role="navigation" id="navbar">
        <div class="container">
            <div class="navbar-nav align-items-center">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'images/ddnobg.png' %}" width="10%" height="10%" alt="" class="d-inline-block align-text-top">
                Door Doctor
                </a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        About Us
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'about' %}">About Us</a>
                        <a class="dropdown-item" href="{% url 'faq' %}">FAQs</a>
                    </div>
                </li> 
                <a class='nav-item nav-link' href="{% url 'gallery' %}" class="btn btn-simple">Gallery</a>
                <a class='nav-item nav-link' href="{% url 'services' %}" class="btn btn-simple">Services</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Installations
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Garage Doors</a>
                        <a class="dropdown-item" href="#">Garage Door Openers</a>

                    </div>
                </li> 
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Customer Testimonials
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'reviews:review_list' %}">Review List</a>
                        <a class="dropdown-item" href="{% url 'reviews:submit_review' %}">Leave a Review</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Contact Us
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'contact' %}">Contact Info</a>
                        <a class="dropdown-item" href="{% url 'appointments:request_appointment' %}">Request Appointment</a>
                    </div>
                </li>  
            </ul>  
            </div>   
             
        </div>
    </nav>

    {% block content %}
    {% endblock %}
    
    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Slick Carousel JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <!-- Custom JS -->
    <script src="{% static 'js/carousel.js' %}"></script>
</body>
</html>

door_doctor/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="text-carousel">
    <!-- Slides -->
    <div class="carousel-slide">Slide 1</div>
    <div class="carousel-slide">Slide 2</div>
    <div class="carousel-slide">Slide 3</div>
</div>
{% endblock %}

door_doctor/templates/faq.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container2">
<h1>Frequently Asked Questions</h1>

<div class="faq-item">
    <h2>Q: Why does my garage door shake when moving up or down?</h2>
    <p>A: This is often caused by failing pulleys. As pulleys wear out, they can start to seize, preventing your garage door from operating smoothly. This is often an easy fix!</p>
</div>

<div class="faq-item">
    <h2>Q: Why do the lights on my garage door opener flash ten times?</h2>
    <p>A: This typically indicates misaligned safety sensors. Fortunately, this is usually a straightforward fix!</p>
</div>

<div class="faq-item">
    <h2>Q: When I try to open my garage door, it lifts a few inches and then closes. What's causing this?</h2>
    <p>A: This issue is likely due to a broken spring. When a spring breaks, the door becomes too heavy for the opener to lift fully, resulting in it only raising a few inches off the ground.</p>
</div>

<div class="faq-item">
    <h2>Q: Can I add Wi-Fi capabilities to my existing garage door opener?</h2>
    <p>A: Yes, this is often possible if your garage door opener is equipped with safety sensors at the bottom of the door.</p>
</div>

<div class="faq-item">
    <h2>Q: Do I need to replace the entire garage door if one of the sections is bent?</h2>
    <p>A: In many cases, depending on the model, we can order individual replacement sections to restore your door without needing a full replacement.</p>
</div>

<div class="faq-item">
    <h2>Q: Do I need a new garage door if I accidentally backed my car into it?</h2>
    <p>A: The need for a replacement depends on the extent of the damage. However, in most cases, we can repair the door so that it functions as it did before the accident.</p>
</div>
</div>

{% endblock %}

door_doctor/templates/gallery.html
{% extends 'base.html' %}

{% block content %}
<h1>GALLERY</h1>
{% endblock %}

door_doctor/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1> Welcome to Door Doctor's Home Page</h1>
{% endblock %}

door_doctor/templates/review_email.html
<!-- review_email.html -->
<!DOCTYPE html>
<html>
<head>
    <title>New Review Submitted</title>
</head>
<body>
    <h1>New Review Submitted</h1>
    <p><strong>Name</strong> {{ name }}</p>
    <p><strong>Street:</strong> {{ street }}</p>
    <p><strong>City:</strong> {{ city }}</p>
    <p><strong>State:</strong> {{ state }}</p>
    <p><strong>ZIP Code:</strong> {{ zip_code }}</p>
    <p><strong>Phone Number:</strong> {{ phone_number }}</p>
    <p><strong>Review Text:</strong> {{ review_text }}</p>
</body>
</html>

door_doctor/templates/servicerepair.html
{% extends 'base.html' %}

{% block content %}

<div class="container3">
    <h1>Service and Repairs</h1>
    <p>We take pride in fully informing our customers of every available option when it comes to repairing their garage doors. 
        A malfunctioning or damaged garage door doesn't always need to be replaced! 
        One of the most common concerns we hear from customers is that other companies often recommend costly replacements when, in many cases, simple repairs can effectively restore function and save both time and money.</p>

    <p>Whether your door has been accidentally damaged or has worn down over time due to weather and environmental factors, there's a strong possibility it can be repaired to look and operate like new. 
        Our service calls range from routine maintenance to addressing broken components such as springs, pulleys, rollers, tracks, cables, and more!</p>

        <h3>Garage Door Repairs</h3>
        <p>It's not uncommon for a family member to accidentally back their car into the garage door. 
        The first concern is often, 'How am I going to get the car out?' quickly followed by, 'How much will it cost to replace the door?' 
        Rest assured, we can promptly get the door open so you can safely remove your vehicle. Afterward, we'll carefully assess the damage and attempt to restore the door back to full functionality. 
        Our customers consistently appreciate our thorough repair process and are often relieved to avoid the expense of a full door replacement.</p>

        <h3>Spring Repairs</h3>
        <p>One of the most common things to break on a garage door are the springs. It is always best to replace these in pairs.</p>

        <h3>Track Repairs</h3>
        <p>Garage door tracks can often become bent or damaged, frequently due to incidents like a car door being left open while pulling out of the garage or other common mishaps. 
            In many cases, the metal tracks can be carefully reshaped using specialized tools, saving you the cost and hassle of a full track replacement.</p>

        <h3>Garage Door Opener Repairs</h3>
        <p>Most garage door motor manufacturers still have parts readily available for your old motor. One common failure point is the gear and sprocket assembly, 
        which can often be replaced to restore your motor back to life for another 15 years!</p>



</div>

{% endblock %}